### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by lucsanara**
Hi!

Could you please update aslprep version?

Thanks in advance

### CODE REVIEW

**Comment by lucsanara** [comment]
Hi! 

I think there has been a bug with this. Could you please keep us updated in case the update successes?

**Comment by stebo85** [comment]
dear @lucsanara - yes, there was a problem, which is fixed now. So the updated version should be live in a couple of hours.

**Comment by lucsanara** [comment]
Dear @stebo85, 
We are struggling when aslprep through Neurodesk. It is arising the following error:
`traits.trait_errors.TraitError:` The 'subjects_dir' trait of a RobustTemplateInputSpec instance must be a pathlike object or string representing an existing directory, but a value of '/home/jovyan/freesurfer-subjects-dir' <class 'str'> was `specified.`
Even when we are not providing --fs-subjects-dir. We have already contacted aslprep developers, though we wanted to ask you it case it could be because of using a singularity container. 
Thank you in advance!

**Comment by stebo85** [comment]
@lucsanara - did any of my suggestions work? If yes, then I can document it.

**Comment by lucsanara** [comment]
@stebo85 sorry for the late reply.
At first it seemed to work, but it then raised a new error: 
Captura de pantalla 2024-10-11 a las 12 04 07
Not sure which is the problem as outside neurodesk it works.

**Comment by stebo85** [comment]
@lucsanara - that's great to know!

What command line options are you running ASLprep with?

What do you mean with "outside neurodesk it works"? Does it mean the singularity/apptainer container works and this error only comes up when running it through the neurodesktop interface?

**Comment by lucsanara** [comment]
Hi! thanks for your answer @stebo85 
Here I show yo the command: 
 aslprep neurodesktop-storage/Agueda/BIDS neurodesktop-storage/Agueda/BIDS/derivatives/aslprep participant --participant-label sub-388 --force-bbr --basil --ignore t2w --fs-subjects-dir /Users/agueda/neurodesktop-storage/Agueda/BIDS/derivatives/freesurfer/sourcedat/freesurfer_pre/sourcedata --bids-filter-file neurodesktop-storage/Agueda/BIDS/BIDS_filter_file.json --fs-license-file neurodesktop-storage/Agueda/BIDS/license.txt --skip_bids_validation -vv -w neurodesktop-storage/Agueda/BIDS
By outside neurodesktop I mean when running aslprep in the computer terminal.

**Comment by stebo85** [comment]
Ok, is this on apple silicon or on an x86 processor? 

If on apple silicon: is it running through podman or docker?

**Comment by stebo85** [comment]
@lucsanara - can you also share the crash file or anything that contains more information about the error? I can currently not reproduce the problem.

**Pull request merged**
