### PR TITLE
Bidscoin 4.3.1 upgrade

### PR DESCRIPTION
**Pull request by marcelzwiers**
This upgrades BIDScoin to the latest version and re-inserts the code for conda-installing some FSL tools (I added this code in my previous PR but it somehow got lost in the merge process)

### CODE REVIEW

**Comment by marcelzwiers** [comment]
I don't understand where these merge conflicts come from. I pulled from master, created a new branch, committed my changes (in Linux) and created this PR. All within an hour or so. I did the same last time and then I also got such merge conflicts, what do I do wrong?

**Comment by marcelzwiers** [comment]
Well, I'll delete this and redo the whole thing

**Comment by marcelzwiers** [comment]
I now get `This branch is 5 commits ahead of, 41 commits behind NeuroDesk/neurocontainers:master.` Well, I'll delete everything and start from scratch

**Comment by stebo85** [comment]
It sounds like you update your fork before creating the branch for this pull request. GitHub has a button for this now (sync fork or sync with upstream - something like this)

**Pull request closed without merging**
