### PR TITLE
Add brkraw

### LINKED ISSUE #601: add brkraw
The ‘BrkRaw’ is a python module designed to provide a comprehensive tool to access raw data acquired from Bruker Biospin preclinical MRI scanner. This module is also compatible with the zip compressed data to enable use of the archived data directly.
The module is comprised of four components, including graphical user interface (GUI), command-line tools, high-level and low-level python APIs.

    For the GUI, we focused on improving convenience for checking metadata and previewing the reconstructed image.
    For the command-line tool, we focused on providing tools for converting, organizing, archiving, and managing data. The command-line tool also provides easy-to-use function to convert large set of raw data into organized structure according to [BIDS](https://bids.neuroimaging.io/).
    For the high-level python API, we focused on enhancing the accessibility of reconstructed image data with preserved image orientation and metadata for the image analysis. It compatible users' convenient objects type ([nibabel](https://nipy.org/nibabel/) or [SimpleITK](https://simpleitk.readthedocs.io/en/master/gettingStarted.html#python-binary-files)) without the conversion step.
    For the low-level python API, we focused on providing a consistent method to access raw Bruker data including parameter and binary files with the python compatible datatype while keeping the sake of simplicity.

### PR DESCRIPTION
**Pull request by Vbitz**
Fixes #601

Builds fine on my local system. May need a updated version of TinyRange on the self-hosted builder.

### CODE REVIEW

**Comment by Vbitz** [comment]
There is a issue with the current version. It creates a python virtual environment in `/root/pyenv`. This is required with Alpine since pip doesn't let you install distribution wide packages. This will need to be fixed before we can merge. Any thoughts @stebo85?

**Comment by stebo85** [comment]
Why build in alpine in the first place? Would Debian / centos work better?


Thank you

Steffen

--

W: https://mri.sbollmann.net<https://mri.sbollmann.net/>  | W: https://www.neurodesk.org<https://www.neurodesk.org/>  | T: https://twitter.com/sbollmann_MRI  | G: https://github.com/stebo85

Book meeting: https://calendly.com/s-bollmann/meeting

________________________________

**Comment by Vbitz** [comment]
I've switched it to Ubuntu. This version works fine.

I started with Alpine to see if I could get the container size a little smaller.

**Comment by stebo85** [comment]
Yes, great it works now :) good idea to start with alpine - one day we will find a package where alpine works well :p


Thank you

Steffen

--

W: https://mri.sbollmann.net<https://mri.sbollmann.net/>  | W: https://www.neurodesk.org<https://www.neurodesk.org/>  | T: https://twitter.com/sbollmann_MRI  | G: https://github.com/stebo85

Book meeting: https://calendly.com/s-bollmann/meeting

________________________________

**Pull request merged**
