### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by lucsanara**
Hello!! 
Could you please update aslprep version to 0.6.0?
Thank you in advance!!

### CODE REVIEW

**Comment by stebo85** [comment]
Thank you so much for proposing the update :)

**Comment by stebo85** [comment]
Dear @lucsanara - the new version is now online. You need to click the update button in the Application menu to see the latest version :) Let us know if everything is working as expected and thank you for the contribution!

image

**Comment by stebo85** [comment]
Dear @lucsanara - intersting. It looks like they assume that the homedirectory of asprep in the image is writable, which of course doesn't work for singularity containers. I see if I can do something about this, if not we need to flag this as a bug in aslprep.

**Comment by lucsanara** [comment]
Dear @stebo85, how is it going? did you manage to solve? 
Thanks in advance!

**Comment by stebo85** [comment]
No, unfortunately no good solution yet

**Comment by stebo85** [comment]
Dear @lucsanara - we have an idea how to fix this without waiting on a fix from ASLprep. I will implement next week and let you know once you can test.

**Comment by lucsanara** [comment]
Great @stebo85!! thanks

**Comment by lucsanara** [comment]
Dear @stebo85, did you manage to solve it? 
Thanks in advance!

**Comment by stebo85** [comment]
No, it doesn’t work yet unfortunately. But we are close to a solution

**Comment by stebo85** [comment]
Dear @lucsanara,

Finally, we found the problem and a solution!

The problem is that the ASLPREP container sets the HOME variable incorrectly to /home/aslprep - but for a singularity container, this needs to be dynamically set to the home directory of the user running the container. We now added this fix in our aslprep container build and we overwrite this wrong variable in our build process.

The new version of aslprep 0.6.0 is now released in Neurodesk, can you test if it also works for you?

Thank you
Steffen

**Comment by lucsanara** [comment]
Hey @stebo85!! 
After working with it for some weeks it worked. However, since last week we are experimenting some troubles. Sometimes process stops after showing the following lines: /cvmfs/neurodesk.ardc.edu.au/containers/aslprep_0.6.0_20240318/aslprep: line 3:  1596 Killed                  singularity --silent exec --cleanenv --env DISPLAY=$DISPLAY $neurodesk_singularity_opts --pwd "$PWD" /cvmfs/neurodesk.ardc.edu.au/containers/aslprep_0.6.0_20240318/aslprep_0.6.0_20240318.simg aslprep "$@"
They are not always stopping at the same points, neither after an error of aslprep, so we don't know what is happening. 
Thanks in advance!!

**Comment by stebo85** [comment]
Are you running this  on an HPC through slurm scheduling? If yes, can you try to increase the memory you give to the job.

otherwise can you reproduce this on play.neurodesk.org? Or on any other computer?

**Comment by stebo85** [comment]
@lucsanara - is there any update on this? Does this problem only happen with this container version or also others? Can you provide more details about the execution environment you are running this in?

**Comment by lucsanara** [comment]
It's working properly. Thanks!!

**Comment by stebo85** [comment]
Ok, thank you for confirming

**Pull request merged**
