### PR TITLE
Bidscoin add fsltools

### PR DESCRIPTION
**Pull request by marcelzwiers**
This is the same bidscoin version (4.3.0) as before, but the container now has support for some fsl tools, so that bidscoin apps that depend on it now work as expected

### CODE REVIEW

**Review by stebo85 — APPROVED** [review]
That’s very cool! Thank you :) I like that fsl now distributes through conda and it doesn’t need everything to be installed.

**Comment by marcelzwiers** [comment]
The funny thing is, it works in your neurodesk base image, but I can't get the same thing to work in the official python base image (which I use in my own apptainer def -file

**Comment by stebo85** [comment]
Oh, interesting- what error do you get in your base image?

**Comment by stebo85** [comment]
Dear @marcelzwiers,

the problem is that your container somehow uses a version of pngappend which relies on libtiff.so.5, but this is not distributed through conda.

Here is the difference between our Neurodesk container:
```
ldd /opt/miniconda-latest/bin/pngappend
	linux-vdso.so.1 (0x00007ffd3595a000)
	libfsl-miscplot.so => /opt/miniconda-latest/bin/../lib/libfsl-miscplot.so (0x00007f8d05764000)
	libfsl-miscpic.so => /opt/miniconda-latest/bin/../lib/libfsl-miscpic.so (0x00007f8d0574b000)
	libfsl-miscmaths.so => /opt/miniconda-latest/bin/../lib/libfsl-miscmaths.so (0x00007f8d05588000)
	libgdc.so => /opt/miniconda-latest/bin/../lib/libgdc.so (0x00007f8d05560000)
	libgd.so.3 => /opt/miniconda-latest/bin/../lib/libgd.so.3 (0x00007f8d054f7000)
	libstdc++.so.6 => /opt/miniconda-latest/bin/../lib/libstdc++.so.6 (0x00007f8d05312000)
	libgcc_s.so.1 => /opt/miniconda-latest/bin/../lib/libgcc_s.so.1 (0x00007f8d052f7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8d05112000)
	liblapack.so.3 => /opt/miniconda-latest/bin/../lib/liblapack.so.3 (0x00007f8d02f30000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8d02e51000)
	libfsl-newimage.so => /opt/miniconda-latest/bin/../lib/libfsl-newimage.so (0x00007f8d02cdb000)
	libfsl-utils.so => /opt/miniconda-latest/bin/../lib/libfsl-utils.so (0x00007f8d02cc3000)
	libfsl-cprob.so => /opt/miniconda-latest/bin/../lib/libfsl-cprob.so (0x00007f8d02cb9000)
	libfsl-NewNifti.so => /opt/miniconda-latest/bin/../lib/libfsl-NewNifti.so (0x00007f8d02c9c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8d02c97000)
	libpng16.so.16 => /opt/miniconda-latest/bin/../lib/./libpng16.so.16 (0x00007f8d02c58000)
	libfontconfig.so.1 => /opt/miniconda-latest/bin/../lib/./libfontconfig.so.1 (0x00007f8d02c0b000)
	libfreetype.so.6 => /opt/miniconda-latest/bin/../lib/./libfreetype.so.6 (0x00007f8d02b52000)
	libjpeg.so.8 => /opt/miniconda-latest/bin/../lib/./libjpeg.so.8 (0x00007f8d02a6c000)
	libtiff.so.6 => /opt/miniconda-latest/bin/../lib/./libtiff.so.6 (0x00007f8d029d9000)
	libwebp.so.7 => /opt/miniconda-latest/bin/../lib/./libwebp.so.7 (0x00007f8d02939000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8d02932000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8d057a6000)
	libgfortran.so.5 => /opt/miniconda-latest/bin/../lib/./libgfortran.so.5 (0x00007f8d02787000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8d02782000)
	libfsl-znz.so => /opt/miniconda-latest/bin/../lib/libfsl-znz.so (0x00007f8d0277c000)
	libz.so.1 => /opt/miniconda-latest/bin/../lib/././libz.so.1 (0x00007f8d02761000)
	libexpat.so.1 => /opt/miniconda-latest/bin/../lib/././libexpat.so.1 (0x00007f8d02730000)
	libzstd.so.1 => /opt/miniconda-latest/bin/../lib/././libzstd.so.1 (0x00007f8d02620000)
	liblzma.so.5 => /opt/miniconda-latest/bin/../lib/././liblzma.so.5 (0x00007f8d025f0000)
	libLerc.so.4 => /opt/miniconda-latest/bin/../lib/././libLerc.so.4 (0x00007f8d0252d000)
	libdeflate.so.0 => /opt/miniconda-latest/bin/../lib/././libdeflate.so.0 (0x00007f8d02517000)
	libsharpyuv.so.0 => /opt/miniconda-latest/bin/../lib/././libsharpyuv.so.0 (0x00007f8d0250b000)
	libquadmath.so.0 => /opt/miniconda-latest/bin/../lib/././libquadmath.so.0 (0x00007f8d024d2000)
```

and you container:
```
ldd /opt/miniconda3/bin/pngappend
	linux-vdso.so.1 (0x00007ffff5d90000)
	libfsl-miscplot.so => /opt/miniconda3/bin/../lib/libfsl-miscplot.so (0x00007fa6aba64000)
	libfsl-miscpic.so => /opt/miniconda3/bin/../lib/libfsl-miscpic.so (0x00007fa6aba4b000)
	libfsl-miscmaths.so => /opt/miniconda3/bin/../lib/libfsl-miscmaths.so (0x00007fa6ab888000)
	libgdc.so => /opt/miniconda3/bin/../lib/libgdc.so (0x00007fa6ab860000)
	libgd.so.3 => /opt/miniconda3/bin/../lib/libgd.so.3 (0x00007fa6ab7f6000)
	libstdc++.so.6 => /opt/miniconda3/bin/../lib/libstdc++.so.6 (0x00007fa6ab611000)
	libgcc_s.so.1 => /opt/miniconda3/bin/../lib/libgcc_s.so.1 (0x00007fa6ab5f6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa6ab411000)
	liblapack.so.3 => /opt/miniconda3/bin/../lib/liblapack.so.3 (0x00007fa6a9230000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa6a9151000)
	libfsl-newimage.so => /opt/miniconda3/bin/../lib/libfsl-newimage.so (0x00007fa6a8fd9000)
	libfsl-utils.so => /opt/miniconda3/bin/../lib/libfsl-utils.so (0x00007fa6a8fc1000)
	libfsl-cprob.so => /opt/miniconda3/bin/../lib/libfsl-cprob.so (0x00007fa6a8fb7000)
	libfsl-NewNifti.so => /opt/miniconda3/bin/../lib/libfsl-NewNifti.so (0x00007fa6a8f9a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa6a8f95000)
	libpng16.so.16 => /opt/miniconda3/bin/../lib/./libpng16.so.16 (0x00007fa6a8f56000)
	libfontconfig.so.1 => /opt/miniconda3/bin/../lib/./libfontconfig.so.1 (0x00007fa6a8f09000)
	libfreetype.so.6 => /opt/miniconda3/bin/../lib/./libfreetype.so.6 (0x00007fa6a8e50000)
	libjpeg.so.9 => /opt/miniconda3/bin/../lib/./libjpeg.so.9 (0x00007fa6a8e12000)
	libtiff.so.5 => not found
	libwebp.so.7 => /opt/miniconda3/bin/../lib/./libwebp.so.7 (0x00007fa6a8d8b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa6a8d84000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa6abaa6000)
	libgfortran.so.5 => /opt/miniconda3/bin/../lib/./libgfortran.so.5 (0x00007fa6a8bd9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa6a8bd4000)
	libfsl-znz.so => /opt/miniconda3/bin/../lib/libfsl-znz.so (0x00007fa6a8bce000)
	libz.so.1 => /opt/miniconda3/bin/../lib/././libz.so.1 (0x00007fa6a8bb3000)
	libxml2.so.2 => /opt/miniconda3/bin/../lib/././libxml2.so.2 (0x00007fa6a8a49000)
	libquadmath.so.0 => /opt/miniconda3/bin/../lib/././libquadmath.so.0 (0x00007fa6a8a10000)
	liblzma.so.5 => /opt/miniconda3/bin/../lib/./././liblzma.so.5 (0x00007fa6a89e0000)
	libicuuc.so.73 => /opt/miniconda3/bin/../lib/./././libicuuc.so.73 (0x00007fa6a87d5000)
	libicudata.so.73 => /opt/miniconda3/bin/../lib/././././libicudata.so.73 (0x00007fa6a694d000)

```

**Comment by stebo85** [comment]
ok, found out one more little detail: the pngappend binaries are identical between the two systems:
12ea9e0078fe5174d2124f304688886b  /opt/miniconda3/bin/pngappend
12ea9e0078fe5174d2124f304688886b  /opt/miniconda-latest/bin/pngappend

**Comment by stebo85** [comment]
but library versions are slightly different:
image

image

**Comment by stebo85** [comment]
Dear @marcelzwiers,

finally found the problem with @Vbitz , but not 100% if we understand fully:

Insert this before your `conda install -c conda-forge -c https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/ fsl-libvis fsl-avwutils fsl-flirt`
```
    conda update -yq -nbase conda
    conda config --set channel_priority strict
    conda config --system --set auto_update_conda false
    conda config --system --set show_channel_urls true 
    conda install python=3.11
```

strangely just updating conda doesn't do it yet, but updating Python to the latest version also updates the underlying libtiff libraries and then it works

**Comment by marcelzwiers** [comment]
It's amazing that you figured this out, I would never have gotten to that myself! I now have a better understanding what happened, and I think the root of the problem was that miniconda changed the base python version and that conda channel ordering needed to be strict (I would have never thought about that). FYI, I now stripped it down to:

```
    # Install the latest miniconda (needed for FSL install). NB: Keep the Python version the same as the Docker base image (i.e. 3.10, currently Miniconda3-latest == py311)
    mkdir -p /opt/miniconda3
    curl https://repo.anaconda.com/miniconda/Miniconda3-py310_23.11.0-2-Linux-x86_64.sh --output /opt/miniconda3/miniconda.sh
    bash /opt/miniconda3/miniconda.sh -b -u -p /opt/miniconda3
    rm -rf /opt/miniconda3/miniconda.sh
    export PATH=/opt/miniconda3/bin:$PATH

    # Install FSL tools
    conda config --set channel_priority strict      # Needed for pngappend, see: https://github.com/NeuroDesk/neurocontainers/pull/598
    conda install -c conda-forge -c https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/ fsl-libvis fsl-avwutils fsl-flirt
```
Thanks again!

**Pull request closed without merging**
