### PR TITLE
Added niimath

### PR DESCRIPTION
**Pull request by Vbitz**

### CODE REVIEW

**Review by stebo85 — CHANGES_REQUESTED** [review]
can you fix the spelling mistakes or add exceptions for them?

**Comment by Vbitz** [comment]
The read me is based on the upstream. One of the spelling is a name in a citation and the other is an American spelling. How do I add exceptions for those?

**Comment by stebo85** [comment]
I think there is a comment feature in this checker that tells it to ignore certain words

**Comment by stebo85** [comment]
True: other option would be to get rid of the spellchecker if it's too tedious

**Comment by Vbitz** [comment]
It's still useful. Maybe switch it to warning only mode?

**Comment by stebo85** [comment]
Yes, you can do that - that's a good idea

**Comment by neurolabusc** [comment]
@stebo85 is there an easy way to have code-spell ignore words or add them to a dictionary. It thinks "Hart" is a typo and suggests "Heart" or "Harm" , but Cameron Hart is the authors name. It seems Codespell (v 2.2.2) still complains if the README.md looks like this:

```
<!-- codespell-ignore-line -->Hart
```

**Comment by Vbitz** [comment]
Fixed the spelling mistakes and switched to the official static build of niimath.

**Comment by Vbitz** [comment]
Changed back to Cameron Hart's full name since codespell is now removed.

**Review by stebo85 — APPROVED** [review]

**Comment by stebo85** [comment]
@neurolabusc - we couldn't get the comment exception of the spellchecker to work and now disabled it.

**Pull request merged**
