### PR TITLE
Create build.sh

### PR DESCRIPTION
**Pull request by thomshaw92**
first test to see if it builds.
#160

### CODE REVIEW

**Comment by stebo85** [comment]
in addition it needs a yml file to trigger the build action under .github/workflows -> follow the template example :)

**Comment by thomshaw92** [comment]
@stebo85 could you link me to the template please? :)

**Comment by stebo85** [comment]
https://github.com/NeuroDesk/neurocontainers/blob/master/.github/workflows/template.yml

**Comment by stebo85** [comment]
you need to copy the template and then rename file and template names with the toolname. Here is the full list of steps: https://www.neurodesk.org/developers/new_tools/add_tool/

**Pull request merged**
