### PR TITLE
update MRSIproc container

### PR DESCRIPTION
**Pull request by korbinian90**
change to container based on FSL -
(manual FSL install fails);
lcmbasis from juchem not existing anymore;
matlab installed manually via mpm;
add julia;
update miniconda+python;
remove libtk8.6 <- asks interactive question (lcmodel);

### CODE REVIEW

**Comment by korbinian90** [comment]
@stebo85 Please merge ;)
I added FSL, which is used for creating the different masks, lipid, skull, brain

**Comment by stebo85** [comment]
@korbinian90 - the current build didn't work yet, because the lcmodel license file was copied in the build script. I removed it now.

I also added space savings in the container by chaining commands (otherwise every run command will lead to a new layer)

and you cannot access .bashrc within a container because it doens't exist yet - so workaround via a modified matlab startup file

**Comment by korbinian90** [comment]
@stebo85 Thanks for looking at the container and fixing issues!

I didn't know about the space savings when chaining, that makes sense!

I removed the matlab startup file workaround as it conflicted with the way matlab is called via the script and I didn't see the benefit. But now it makes sense, in the script I can just call matlab with the full path and the -c option to specify the license location to avoid conflicts.

For me locally, the build crashed now because "rm: cannot remove '/usr/local/bin/matlab': No such file or directory"
Maybe this is because I changed the user to root. Otherwise I got some permission denied error that I didn't understand during the docker build.
But the matlab workaround is not necessary for the mrsi script as it uses the -c option. We would just need that to open matlab with the GUI (which I would like to remove soon anyway).

Weirdly this .bashrc way worked for me in the locally created docker test, maybe because I used root as user?

I'm currently trying to use matlab compiler to compile the scripts and run them with the matlab compiler runtime, that doesn't require a license. I'm currently updating the container again to install the matlab compiler runtime additionally.

**Comment by stebo85** [comment]
ahh, ok - then we can remove the matlab fix for now - maybe the executable of matlab doens't get saved in that location. 

yes, the .bashrc will work if you stay in pure docker, but because we convert the images to singularity it will load the user's homedirectory during runtime - so anything modified there will not be available. 

Running everything with the matlab runtime would be fantastic :): Here is a an example for the compiler runtime: https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/spm12/build.sh

**Comment by korbinian90** [comment]
The --matlabmcr installer via neurodocker has some url Problem and doesn't install. I downloaded it now manually and install it. This works, but it is 8.5GB in size as it Installs all toolboxes. It should be possible to specify only certain ones, but I didn't get it working yet.
Is the 8.5GB size a problem?

**Comment by stebo85** [comment]
Ok, I have a look at the url error - but manual works for now and the size is no problem

**Pull request merged**
