### PR TITLE
mfcsc 1.1

### PR DESCRIPTION
**Pull request by civier**
New version of mfcsc with actual test scripts that download test data and run it through the tool (/neurodessk/app_test.sh & /neurodesk/app_version.sh)

### CODE REVIEW

**Review by stebo85 — APPROVED** [review]

**Comment by stebo85** [comment]
Dear @civier - your pull request creates merge conflicts, so it's not possible to merge it. Please resolve the conflicts.

**Review by stebo85 — CHANGES_REQUESTED** [review]
Dear @civier - your pull request cannot be merged. You need to solve conflicts first. Can you please rebase your branch, solve the conflicts and then push again?

**Comment by civier** [comment]
I believe I resolved all conflicts. Can you merge?

**Comment by stebo85** [comment]
no, doesn't work yet - so you can rebase on your side ok? Did you pull into master before rebasing?

**Comment by civier** [comment]
I don't really get it, I did "git checkout origin", then "git pull upstream master", resolved conflicts, "git add <updated files>, and "git commit". Now it says that the merge can be done automatically, so I assume it's all ok:
Screen Shot 2023-03-20 at 4 05 45 pm
If there are still conflicts, how can I see them?

**Comment by stebo85** [comment]
Dear Oren,

I think I found what's wrong: You broke your master branch in your fork. You need to move your changes to a feature branch in your fork, then you need to reset the master branch to upstream, then you need to rebase your feature branch to the corrected master branch, then you need to open a new pull request from the feature branch against our master branch. Once merged you can resync. Closing this one here, because it's not really fixable.

As a general rule: never commit to master - especially not when working in a fork - that already caused the CI problems when you were directly committing to our master branch.

**Comment by civier** [comment]
Thanks for the clarifications @stebo85,

I rather delete my current fork, fork neurocontainers anew, and do everything from the beginning. However, to make sure I (and other developers) do things according to the recommend way (there are just too many options in git, and online guides are thus limited in utility), I'd appreciate if you could document all the required git commands in the step-by-step guide here:
https://www.neurodesk.org/developers/new_tools/add_tool/#create-a-new-app
Right now the guide assumes that all container developers are directly updating the upstream repository, which is not the case anymore.

Thanks,
Oren

**Comment by stebo85** [comment]
Dear @civier,

the documentation is already up-to-date and I am not sure what's missing. 

It clearly says to fork and it recommends to use a feature branch: https://www.neurodesk.org/developers/new_tools/cloning/


Also, since the github workflow is too difficult for some people, we now have a new contribution workflow that's documented here: https://www.neurodesk.org/docs/neurocontainers/contribute/

it also states that the "developer" workflow is not recommended if you are not familiar with git: https://www.neurodesk.org/developers/new_tools/add_tool/#adding-new-tools-via-our-interactive-container-builder

Kind regards
Steffen

**Comment by civier** [comment]
I'd be happy to test the new contribution workflow if it makes my life easier.

I'm familiar with git, but as you know, there are levels of familiarity. It is one thing to do commit, push and pull, and another thing to manage pull requests, rebasing, etc.

In any case, what is not up to date is the documentation in
https://www.neurodesk.org/developers/new_tools/add_tool/#step-by-step-guide
as it assumes that people directly update the upstream repository with pull and push.
So either update it or add a depreciation notice, I would say.

**Comment by stebo85** [comment]
Dear @civier, 

If you scroll up a bit in the documentation you find the link to how to setup the fork correctly: 
image

That link brings you to the detailed instructions:
image

I added you to the new interactive build tool - so you can try that out.

Kind regards
Steffen

**Pull request closed without merging**
